[[type]]
name = "Task"
slug = "task"

[[status]]
name = "To Do"
slug = "todo"

[[status]]
name = "In Progress"
slug = "progress"
category = 10

[[status]]
name = "Done"
slug = "done"
category = 80

[[priority]]
name = "Low"
slug = "low"
value = -10

[[priority]]
name = "Normal"
slug = "normal"
value = 0

[[priority]]
name = "High"
slug = "high"
value = 50

[[priority]]
name = "Critical"
slug = "critical"
value = 100

[[transition]]
type = "task"
name = "Initial"
slug = "initial"
initial = true
to_status = "todo"
from_any_status = true

[[transition]]
type = "task"
name = "In Progress"
slug = "in-progress"
to_status = "progress"
from_any_status = true

[[transition]]
type = "task"
name = "Mark Done"
slug = "mark-done"
verbs = "done"
to_status = "done"
from_statuses = ["progress"]
